### Numpy

In [2]:
import numpy as np

In [17]:
a=[
    [1,2,3],
    [4,5,6],
    [4,5,6]
]
b=[
    [6,7,8],
    [4,5,6],
    [1,2,3]
]

In [18]:
a = np.array(
    [
    [6,7,8],
    [4,5,6],
    [1,2,3]
])

In [19]:
a[1][1]

np.int64(5)

In [20]:
a[1,1]

np.int64(5)

In [21]:
a[1:,1:]

array([[5, 6],
       [2, 3]])

In [22]:
#The biggest power of numpy is boardcasting...
a+1


array([[7, 8, 9],
       [5, 6, 7],
       [2, 3, 4]])

In [28]:
b = a*1.0
b

array([[6., 7., 8.],
       [4., 5., 6.],
       [1., 2., 3.]])

In [29]:
a.dtype

dtype('int64')

In [30]:
b.dtype

dtype('float64')

In [31]:
a + np.array([1,2,3])

array([[ 7,  9, 11],
       [ 5,  7,  9],
       [ 2,  4,  6]])

In [33]:
a + np.array([1,2,3])

array([[ 7,  9, 11],
       [ 5,  7,  9],
       [ 2,  4,  6]])

In [35]:
print(a)
a.T #Transpose of matrix

[[6 7 8]
 [4 5 6]
 [1 2 3]]


array([[6, 4, 1],
       [7, 5, 2],
       [8, 6, 3]])

In [36]:
(a + np.array([1,2,3])).T

array([[ 7,  5,  2],
       [ 9,  7,  4],
       [11,  9,  6]])

In [40]:
np.array([[1,2,3]])

array([[1, 2, 3]])

In [41]:
a

array([[6, 7, 8],
       [4, 5, 6],
       [1, 2, 3]])

In [43]:
b = np.array([[1,2,3],[4,5,6],[7,8,9]])
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [44]:
a+b

array([[ 7,  9, 11],
       [ 8, 10, 12],
       [ 8, 10, 12]])

In [45]:
a-b

array([[ 5,  5,  5],
       [ 0,  0,  0],
       [-6, -6, -6]])

In [46]:
a*b #this is just multiplication with the respective element

array([[ 6, 14, 24],
       [16, 25, 36],
       [ 7, 16, 27]])

In [47]:
a/b

array([[6.        , 3.5       , 2.66666667],
       [1.        , 1.        , 1.        ],
       [0.14285714, 0.25      , 0.33333333]])

In [48]:
a@b #This is the matrix multiplication

array([[ 90, 111, 132],
       [ 66,  81,  96],
       [ 30,  36,  42]])

In [52]:
#All zero array, all 1 array, random element array
np.zeros((3,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [74]:
np.ones_like(a,shape = (10,10))

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [60]:
np.random.randint(5,10,(2,3))

array([[9, 6, 7],
       [6, 5, 6]])

In [79]:
marks = np.random.randint(80,100,size=(10,4))
marks

array([[80, 90, 88, 88],
       [90, 96, 82, 91],
       [85, 81, 99, 94],
       [87, 83, 85, 83],
       [97, 82, 90, 99],
       [83, 89, 98, 83],
       [90, 87, 91, 97],
       [90, 80, 84, 87],
       [82, 85, 80, 91],
       [83, 94, 98, 95]])

In [80]:
dir(marks)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_namespace__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__buffer__',
 '__class__',
 '__class_getitem__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__dlpack__',
 '__dlpack_device__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',


In [86]:
# help(marks)

In [85]:
marks.sum()

np.int64(3537)

In [87]:
marks.mean()

np.float64(88.425)

In [88]:
marks.max()

np.int64(99)

In [89]:
marks.min()

np.int64(80)

In [94]:
marks.sort()

In [105]:
np.max(marks, axis=1)

array([90, 96, 99, 87, 99, 98, 97, 90, 91, 98])

In [106]:
max_value = np.amax(marks[0])
print(max_value)  # Output: 9

90


In [124]:
np.min(marks, axis=1)

array([80, 82, 81, 83, 82, 83, 87, 80, 80, 83])

In [127]:
#Printing percentage of each students
print("Percentage = ",(np.sum(marks,axis=1))/4)

Percentage of each=  [86.5  89.75 89.75 84.5  92.   88.25 91.25 85.25 84.5  92.5 ]


In [129]:
#Finding average in a row (first subject)
row,col = marks.shape
print("Avg marks of each subject: ", np.sum(marks,axis=0)/row)

Avg marks of each subject:  [82.1 86.9 90.2 94.5]


In [136]:
np.full((6,8),fill_value=9)

array([[9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9]])

In [135]:
marks[marks>95]

array([96, 99, 97, 99, 98, 97, 98])